type Contract = {
    id: number;
    id_empleado: number;
    periodoOrdinarioPago: string;
    fechaAsignada: string;
    montoSueldoMensual: number;
    montoJornalDiario: number;
    montoPorHora: number;
    diasCalculoJornal: number;
    claseTrabajoARealizar: string;
    lugarPrestacion: string;
    lugarPrestacionPersonalizado: string | null;
    formaContrato: string;
    periodoPrueba: number;
    observacionesFormaContrato: string;
    plazoContrato: string;
    fechaInicioTareas: string;
    fechaIngresoEmpresa: string;
    jornadaTrabajo: string;
    horarioMañanaDesde: number;
    horarioMañanaHasta: number;
    horarioTardeDesde: number;
    horarioTardeHasta: number;
    horarioSabadosDesde: number;
    horarioSabadosHasta: number;
    horarioDomingosDesde: number;
    horarioDomingosHasta: number;
    alimentacionGs: string;
    habilitacionGs: string;
    uniformeGs: string;
    cantidadMaterialesEmpleador: number;
    calidadMaterialesEmpleador: string;
    estadoYCondicionesDeEntregaMaterialesEmpleador: string;
    observacionesMaterialesEmpleador: string;
    cantidadMaterialesTrabajador: number;
    calidadMaterialesTrabajador: string;
    comisionMaterialesTrabajador: number;
    estadoYCondicionesDeEntregaMaterialesTrabajador: string;
    observacionesMaterialesTrabajador: string;
    camposAMano: string;
    observacionesCamposAMano: string;
};

export default Contract;
